# Generated by Django 5.0.6 on 2024-05-18 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro_users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usuarios',
            new_name='Usuario',
        ),
    ]
